name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: install node 
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          
      - name: Run Trivy vulnerability scanner in fs mod
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-files.sarif'
          trivy-config: trivy.yaml
      - name: Upload SARIF results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-fileresult
          path: trivy-files.sarif


      - name: docker login1
        uses: docker/login-action@v3
        with:
          username: ${{secrets.docker_username}}
          password: ${{secrets.docker_password}}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{secrets.docker_username}}/mohannode:1.0'   
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: bulding and pushing the docker image to the dockerr GitHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{secrets.docker_username}}/mohannode:1.0
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{secrets.docker_username}}/mohannode:1.0'
          format: 'sarif'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
      
      - name: Upload SARIF results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.sarif
      
