name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: install node 
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
      - name: docker login1
        uses: docker/login-action@v3
        with:
          username: ${{secrets.docker_username}}
          password: ${{secrets.docker_password}}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{secrets.docker_username}}/mohannode:1.0'   
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: bulding and pushing the docker image to the dockerr GitHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.docker_username}}/mohannode:1.0
      
